add_subdirectory(AppDrawer)
add_subdirectory(AxisControl)
add_subdirectory(Button)
add_subdirectory(Canvas)
add_subdirectory(Containers)
add_subdirectory(ExtruderControl)
add_subdirectory(Graph)
add_subdirectory(Heatmap)
add_subdirectory(Icon)
add_subdirectory(Input)
add_subdirectory(LVGL)
add_subdirectory(MessageBox)
add_subdirectory(Screen)
add_subdirectory(Theme)
