add_subdirectory(generated)

target_sources(
  DuetScreen.lib
  PRIVATE 
  ${CMAKE_CURRENT_SOURCE_DIR}/LvAnim.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvCheckbox.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/Transitions.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvContainer.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvDropdown.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvImage.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvKeyboard.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvLabel.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvObj.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvSpan.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvSubject.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvSwitch.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvTextarea.cpp
  ${CMAKE_CURRENT_SOURCE_DIR}/LvXml.cpp
)
